spring:
  application:
    name: urlshortener

  data:
    redis:
      host: localhost
      port: 6379
      # password: yourpassword
      # timeout: 2000ms

    mongodb:
      uri: mongodb://admin:secret@localhost:27017/library?authSource=admin
      # database: library

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,prometheus

logging:
  level:
    root: INFO
    com.example.urlshortener: DEBUG